name: rophotographix
favicon: null
layout_spectrum: 0.6490852541755885
typography_spectrum: 0.707552965497598
title: Robert Orcutt Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2430231086909771
  lightness: 0.7459589415229857
  saturation: 0.9294342075008899
  rhythmicContrast: 0.6476734783500433
purpose: []
