name: rophotographix
favicon: null
layout_spectrum: 0.86059
typography_spectrum: 0.61354
title: Robert Orcutt Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fdfcfd'
    - '#27344a'
    - '#bbc9e0'
    - '#4f5c74'
  brandStrength: 0.25
  lightness: 0.25
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
